version: "3"

services:
  # web client
  client:
    build: ./client
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_URL=http://server:8000
    ports:
      - "4173:4173"
    depends_on:
      - server

  # backend server
  server:
    build: ./server
    environment:
      - NODE_ENV=production
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_URL=db
      - MONGO_PORT=27017
      - MONGO_DATABASE=flexmoney
    ports:
      - "8000:8000"
    depends_on:
      - db

  # database
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # database admin
  ui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
    depends_on:
      - db
